language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE byodogs_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: HdxZnCtVYetRrEYBV46ZbooiDNS6M9gwtWdLrqDBsf1xs02zBZ1RKkoMQV+bswguPSLAfzcYR9VrZctezYH6IQQaS5LwdStrUB5GP9PpAuFbMD3KYggKz+SU9MaBxm5ep4o7kOObvV/i2KKywUHsdgAL+oL3bheVCZCGknYk6iff7DTTpFkB4DAjcbXkhkt8k8rwS0dA8iprcmNaiQXBGv2HzztPloXK1AYn87N3TvYx2pxyxLqS+aZ5wawvqxBTbQWa2cYB1J86VEMXGvDdDezdfRnltTJvhkZyly2d32kOEKBGnT7M1EDWYmT4VXk0JO5d8XZw3s6tcvi32NJd5fatmhmE/G9ekBQyN7YsbMnoxYlRSBigUg+yRzVc5YNu+Yu0n2XsP4sHGUqjm6+saVHYq9TBMo7nhMG2TxJZ/kcTjf7EZDBDo5eB2fU2OwZnACOs2lsnR63spEE9L7uyp1SUFDyizR2BL3PM5mnFwSDVmSGPT6aB8pXovzWVtRGDQTzacoBxYdPh7VyiXj446ihn6hAPp/qPQrjuKmRkV3Z6OrCTjHI2/vOv3J8wTv3FExTxllOjtFiB4zjo3nG0AqJOV2aaOdn1UmNJE+GqnKLF72cDZEy2N6A9d0pIFQezXQUjg2u6hUXp4MzyWU1/umjQ+hR+wDZP+LldZdCvNo0=
  app: byodogparty
  on:
    repo: tdberg21/byob
